### ISSUE TITLE
3.3volt just kills it

### ISSUE THREAD

**Issue by HenkVelthoven** [hsanjuan/dccpi#5]
Hello Hector,

First of all thanks for the example setup. I have got i working with an older model raspberry PI B. 

The first thing i noticed is that when i connect all the wires nothing happens. However when taken the 3.3v out away from the booster i am able to run the train. I do not know where to troubleshoot because the lack of electronic skill tend tot amaze me.

Surely i would be more then willing tot upload some pictures as to give you an idea. But perhaps you can clarify the reason for the 3.3 volt going in to the chip?

Kind regards,
Henk

**Comment by hsanjuan** [comment]
Hi @henk1977! I'm glad to see things are more or less working.

According to the diagram the 3.3v goes to the BRK (Brake) input pin in the chip. This effectively removes any signal from the outputs. Note there is a pull-up resistance which makes sure that the break is enabled when GPIO27 is undefined. By setting GPIO27 to LOW, the brake is disabled and you get meaninful output from the chip to the tracks.

Perhaps you are not disabling the break with the software, so you only see it work when disconnecting the 3.3v input. `controller.start()` should do it so it's probably not that. Perhaps your GPIO27 is not correctly wired to BRK, or something is wrong in the diagram (I can't double check now).
