### ISSUE TITLE
pull request to change the version of python use in dccpi to python3.8

### ISSUE THREAD

**Issue by samFabrice** [hsanjuan/dccpi#7]
Hello ,
My name is samFabrice and I am using your library in a project I am doing. You can find it on github. The name of the project is speed. (PADR crystal speed)
Actually since in my project I use the pint library which only works with the version of python> = 3.7 I would like you to update your setup so that we can use python3.8

**Comment by hsanjuan** [comment]
Can you make the PR to upgrade it? I'm happy dropping python2 support.
