### ISSUE TITLE
Use dccpi to control switches on the rails

### ISSUE THREAD

**Issue by samFabrice** [hsanjuan/dccpi#9]
Hello
I managed to use your library for my project and it works really great.
Currently I would like to drive train accessories such as brain motors which control the switches on the rails. except that I may be wrong but I don't see any function in your api that allows me to do this. Can you help me ?
thank you

**Comment by hsanjuan** [comment]
Usually, any other type of device on the tracks is just another DCC-enabled device with an address and functions.

Thus, you can consider your motors/track switches a `DCCLocomitive`. The way you trigger the switches is using setting the fl, f1-f4 fields (dcc functions) to true/false. That would usually make the decoder power it's wires which would make the track switches open/close. These "Locomotives" do not have speed/direction, just functions...

**Comment by samFabrice** [comment]
Thank you for your help I will do it and I will keep you informed
Best wishes

**Comment by hsanjuan** [comment]
Thanks, closing in the meantime.
